### ISSUE TITLE
Problem installing package

### ISSUE THREAD

**Issue by allanbarbosa** [evotodi/seed-bundle#1]
Hello,

I trying to install the package today on my Symfony 5 project and the result of the install was that:

> Symfony operations: 1 recipe (c6066709614dd5d874c4a146696fdb0a)
>   - Configuring evotodi/seed-bundle (>=1.3): From auto-generated recipe
> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 1
> !!  
> !!  In EvotodiSeedExtension.php line 25:
> !!                                                            
> !!    EvotodiSeedBundle config file is missing the namespace  
> !!                                                            
> !!  
> !!  
> Script @auto-scripts was called via post-update-cmd
> 
> Installation failed, reverting ./composer.json to its original content.

Can you help me to resolve this problem?

Thank you

**Comment by evotodi** [comment]
Allan,
Try creating the config file and directory first, then running composer update.
I know it is possible to do during the bundle install but am unsure how do it.

**Comment by allanbarbosa** [comment]
Hi, the installation works. Now i will try to execute the seed functions.

Thank you so much.
