### ISSUE TITLE
Using PasswordEncoderInterface in the Seed

### ISSUE THREAD

**Issue by allanbarbosa** [evotodi/seed-bundle#2]
Hi, good night.

In the example that you demonstrate, you are using the $this->passwordEncoder->encodePassword($userRepo, $user['password']), but i didn't where you initiate it.

Can you explain how you can use this?

Att,
Allan Barbosa

**Comment by evotodi** [comment]
Allan, I am out of town this week and away from my comp. Dependency injection. Create a construct method and inject the needed service. Possibly have to call the parents construct at end of yours.
Try a Google search for symfonycasts dependency injection. They have a great vid on how to.

**Comment by allanbarbosa** [comment]
evotodi, thank you very much. I managed to solve it. I would like to suggest an update to your readme to put a constructor in the sample code with the obtaining of the security property to perform the password encode.

**Comment by mbrodala** [comment]
@allanbarbosa Can you elaborate on how you solved it? I can see here that seeds are added with a hardcoded list of arguments, so adding more constructor arguments for DI doesn't work:

https://github.com/evotodi/seed-bundle/blob/1.3/src/Core/Loader.php#L44

**Comment by mbrodala** [comment]
OK, I found one solution now by explicitly registering my seed as alias for the [expected service name pattern](https://github.com/evotodi/seed-bundle/blob/1.3/src/Core/Loader.php#L36-L39) in the mentioned `Loader`. My `config/services.yaml` now:

```yaml
services:
    # ...
    seed.command.myseed:
        alias: App\Seeds\MySeed
        public: true
```

**Comment by allanbarbosa** [comment]
Hello @mbrodala, i only instanciate the ContainerInterface object in the constructor and call the secutiry.password_encoder from the container object.

I would like to suggest to @evotodi to create a method to execute  the seeds in a defined order. Like the Seeds on Laravel Framework, there is a class called DatabaseSeed and we register the Seed Class in order to call it.
