### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by RosanaAssy** [evotodi/seed-bundle#6]
Hello, will there be Symfony 7 support?

**Comment by fouadSalkini** [comment]
+1

**Comment by ahmad-chauk-sync** [comment]
please i need your support for symfony 7

**Comment by evotodi** [comment]
@RosanaAssy yes there will probably be Symfony 7 support. However it will be a while as I have other projects that must be upgraded first. 
Someone is welcome to create a pull request for the upgrade in the mean time.

**Comment by fouadSalkini** [comment]
@evotodi 
A pull request has been created successfully. #8

**Comment by RosanaAssy** [comment]
@fouadSalkini  Thank you for your effort. @evotodi  Could you please merge it?

**Comment by evotodi** [comment]
Symfony 7.0 support has been added
